name: Build kernel

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison dwarves libssl-dev libelf-dev bc libncurses-dev clang

    - name: Build it
      run: |
        make CC=clang KCONFIG_CONFIG=Microsoft/config-wsl

    - name: Upload kernel
      uses: actions/upload-artifact@v3
      with:
        name: bzImage
        path: arch/x86/boot/bzImage
